#! /usr/bin/env bash

file="forward.zig"
binf="${file%.*}"
bdir="build"

zig build-exe --strip -static -O ReleaseFast "${file}"
zig build-exe --strip -static -O ReleaseFast -target x86_64-windows.win10_rs4 "${file}"

mkdir -p "${bdir}"
mv "${binf}" "${bdir}/zig-${binf}"
mv "${binf}.exe" "${bdir}/zig-${binf}.exe"
