// Code generated by go-swagger; DO NOT EDIT.

package packages

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new packages API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for packages API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
AddPackage creates a new builder package

Create a new package
*/
func (a *Client) AddPackage(params *AddPackageParams, authInfo runtime.ClientAuthInfoWriter) (*AddPackageOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewAddPackageParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "addPackage",
		Method:             "POST",
		PathPattern:        "/packages",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &AddPackageReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*AddPackageOK), nil

}

/*
ListPackages lists of builder packages

Retrieve a list of all valid builder packages
*/
func (a *Client) ListPackages(params *ListPackagesParams, authInfo runtime.ClientAuthInfoWriter) (*ListPackagesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListPackagesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "listPackages",
		Method:             "GET",
		PathPattern:        "/packages",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListPackagesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListPackagesOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
