run:
  skip-dirs:
    - vendor
  skip-files:
    - ".*_test.go"

linters:
  # Disable all and re-enable the default linters as a starting point.
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused