run:
  skip-dirs:
    - vendor

linters-settings:
  errcheck:
    exclude-functions:
      - (*github.com/ActiveState/termtest.ConsoleProcess).Expect
      - (*github.com/ActiveState/termtest.ConsoleProcess).ExpectExitCode
      - (*github.com/ActiveState/termtest.ConsoleProcess).ExpectNotExitCode
      - (*github.com/ActiveState/termtest.ConsoleProcess).ExpectRe
      - (*github.com/ActiveState/termtest.ConsoleProcess).ExpectLongString
      - (*github.com/ActiveState/termtest.ConsoleProcess).WaitForInput

# When issues occur with linting us the snippet below to help with debugging
# linters:
#   # Disable all and re-enable the default linters as a starting point.
#   disable-all: true
#   enable:
#     - errcheck
#     - gosimple
#     - govet
#     - ineffassign
#     - staticcheck
#     - typecheck
#     - unused