# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  - master

resources:
  containers:
  - container: linux
    image: golang:1.12.1

jobs:

  - job: build_linux
    pool:
      vmImage: 'ubuntu-16.04'
    container: linux
    steps:
      - script: |
          export GOFLAGS=-mod=vendor
          go version
          go run scripts/constants-generator/main.go -- internal/constants/generated.go
          go build -o ./build/state -ldflags="-s -w" ./state
        displayName: 'Build'
