// Code generated by go-swagger; DO NOT EDIT.

package ingredients

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListIngredientVersionsParams creates a new ListIngredientVersionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListIngredientVersionsParams() *ListIngredientVersionsParams {
	return &ListIngredientVersionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListIngredientVersionsParamsWithTimeout creates a new ListIngredientVersionsParams object
// with the ability to set a timeout on a request.
func NewListIngredientVersionsParamsWithTimeout(timeout time.Duration) *ListIngredientVersionsParams {
	return &ListIngredientVersionsParams{
		timeout: timeout,
	}
}

// NewListIngredientVersionsParamsWithContext creates a new ListIngredientVersionsParams object
// with the ability to set a context for a request.
func NewListIngredientVersionsParamsWithContext(ctx context.Context) *ListIngredientVersionsParams {
	return &ListIngredientVersionsParams{
		Context: ctx,
	}
}

// NewListIngredientVersionsParamsWithHTTPClient creates a new ListIngredientVersionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListIngredientVersionsParamsWithHTTPClient(client *http.Client) *ListIngredientVersionsParams {
	return &ListIngredientVersionsParams{
		HTTPClient: client,
	}
}

/* ListIngredientVersionsParams contains all the parameters to send to the API endpoint
   for the list ingredient versions operation.

   Typically these are written to a http.Request.
*/
type ListIngredientVersionsParams struct {

	// IngredientID.
	//
	// Format: uuid
	IngredientID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list ingredient versions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListIngredientVersionsParams) WithDefaults() *ListIngredientVersionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list ingredient versions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListIngredientVersionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list ingredient versions params
func (o *ListIngredientVersionsParams) WithTimeout(timeout time.Duration) *ListIngredientVersionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list ingredient versions params
func (o *ListIngredientVersionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list ingredient versions params
func (o *ListIngredientVersionsParams) WithContext(ctx context.Context) *ListIngredientVersionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list ingredient versions params
func (o *ListIngredientVersionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list ingredient versions params
func (o *ListIngredientVersionsParams) WithHTTPClient(client *http.Client) *ListIngredientVersionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list ingredient versions params
func (o *ListIngredientVersionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIngredientID adds the ingredientID to the list ingredient versions params
func (o *ListIngredientVersionsParams) WithIngredientID(ingredientID strfmt.UUID) *ListIngredientVersionsParams {
	o.SetIngredientID(ingredientID)
	return o
}

// SetIngredientID adds the ingredientId to the list ingredient versions params
func (o *ListIngredientVersionsParams) SetIngredientID(ingredientID strfmt.UUID) {
	o.IngredientID = ingredientID
}

// WriteToRequest writes these params to a swagger request
func (o *ListIngredientVersionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ingredientID
	if err := r.SetPathParam("ingredientID", o.IngredientID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
