// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetLogoutParams creates a new GetLogoutParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetLogoutParams() *GetLogoutParams {
	return &GetLogoutParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetLogoutParamsWithTimeout creates a new GetLogoutParams object
// with the ability to set a timeout on a request.
func NewGetLogoutParamsWithTimeout(timeout time.Duration) *GetLogoutParams {
	return &GetLogoutParams{
		timeout: timeout,
	}
}

// NewGetLogoutParamsWithContext creates a new GetLogoutParams object
// with the ability to set a context for a request.
func NewGetLogoutParamsWithContext(ctx context.Context) *GetLogoutParams {
	return &GetLogoutParams{
		Context: ctx,
	}
}

// NewGetLogoutParamsWithHTTPClient creates a new GetLogoutParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetLogoutParamsWithHTTPClient(client *http.Client) *GetLogoutParams {
	return &GetLogoutParams{
		HTTPClient: client,
	}
}

/* GetLogoutParams contains all the parameters to send to the API endpoint
   for the get logout operation.

   Typically these are written to a http.Request.
*/
type GetLogoutParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get logout params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLogoutParams) WithDefaults() *GetLogoutParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get logout params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLogoutParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get logout params
func (o *GetLogoutParams) WithTimeout(timeout time.Duration) *GetLogoutParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get logout params
func (o *GetLogoutParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get logout params
func (o *GetLogoutParams) WithContext(ctx context.Context) *GetLogoutParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get logout params
func (o *GetLogoutParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get logout params
func (o *GetLogoutParams) WithHTTPClient(client *http.Client) *GetLogoutParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get logout params
func (o *GetLogoutParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetLogoutParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
