#! /usr/bin/env bash

x="build/$(basename "${PWD}")"

go build -o "${x}" -ldflags="-s -w"
export GOOS=windows

go build -o "${x}".exe -ldflags="-s -w"

rm "${x}-packed" > /dev/null
upx "${x}" -o "${x}-packed" > /dev/null
