// Code generated by go-swagger; DO NOT EDIT.

package projects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAddBranchParams creates a new AddBranchParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddBranchParams() *AddBranchParams {
	return &AddBranchParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddBranchParamsWithTimeout creates a new AddBranchParams object
// with the ability to set a timeout on a request.
func NewAddBranchParamsWithTimeout(timeout time.Duration) *AddBranchParams {
	return &AddBranchParams{
		timeout: timeout,
	}
}

// NewAddBranchParamsWithContext creates a new AddBranchParams object
// with the ability to set a context for a request.
func NewAddBranchParamsWithContext(ctx context.Context) *AddBranchParams {
	return &AddBranchParams{
		Context: ctx,
	}
}

// NewAddBranchParamsWithHTTPClient creates a new AddBranchParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddBranchParamsWithHTTPClient(client *http.Client) *AddBranchParams {
	return &AddBranchParams{
		HTTPClient: client,
	}
}

/* AddBranchParams contains all the parameters to send to the API endpoint
   for the add branch operation.

   Typically these are written to a http.Request.
*/
type AddBranchParams struct {

	// Body.
	Body AddBranchBody

	/* ProjectID.

	   project ID

	   Format: uuid
	*/
	ProjectID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add branch params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddBranchParams) WithDefaults() *AddBranchParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add branch params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddBranchParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add branch params
func (o *AddBranchParams) WithTimeout(timeout time.Duration) *AddBranchParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add branch params
func (o *AddBranchParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add branch params
func (o *AddBranchParams) WithContext(ctx context.Context) *AddBranchParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add branch params
func (o *AddBranchParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add branch params
func (o *AddBranchParams) WithHTTPClient(client *http.Client) *AddBranchParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add branch params
func (o *AddBranchParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the add branch params
func (o *AddBranchParams) WithBody(body AddBranchBody) *AddBranchParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the add branch params
func (o *AddBranchParams) SetBody(body AddBranchBody) {
	o.Body = body
}

// WithProjectID adds the projectID to the add branch params
func (o *AddBranchParams) WithProjectID(projectID strfmt.UUID) *AddBranchParams {
	o.SetProjectID(projectID)
	return o
}

// SetProjectID adds the projectId to the add branch params
func (o *AddBranchParams) SetProjectID(projectID strfmt.UUID) {
	o.ProjectID = projectID
}

// WriteToRequest writes these params to a swagger request
func (o *AddBranchParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param projectID
	if err := r.SetPathParam("projectID", o.ProjectID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
