// Code generated by go-swagger; DO NOT EDIT.

package headchef_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// BuildRequestedResponse Build Requested Response
//
// A response indicating that a build for the specified recipe has already been requested.
// swagger:model BuildRequestedResponse
type BuildRequestedResponse interface{}
