// Code generated by go-swagger; DO NOT EDIT.

package headchef_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// BuildFailedResponse Build Failed Response
//
// A response indicating that a build failed.
// swagger:model BuildFailedResponse
type BuildFailedResponse struct {
	BuildFailed

	BuildStatus
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *BuildFailedResponse) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 BuildFailed
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.BuildFailed = aO0

	// AO1
	var aO1 BuildStatus
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.BuildStatus = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m BuildFailedResponse) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.BuildFailed)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.BuildStatus)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this build failed response
func (m *BuildFailedResponse) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with BuildFailed
	if err := m.BuildFailed.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with BuildStatus
	if err := m.BuildStatus.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *BuildFailedResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BuildFailedResponse) UnmarshalBinary(b []byte) error {
	var res BuildFailedResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
