// Code generated by go-swagger; DO NOT EDIT.

package headchef_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1SubSchemaRequirementsItems v1 sub schema requirements items
//
// swagger:model v1SubSchemaRequirementsItems
type V1SubSchemaRequirementsItems struct {

	// The operator used to compare the sortable_version against a given provided feature to determine if it meets the requirement
	// Required: true
	// Enum: [eq gt gte lt lte ne]
	Comparator *string `json:"comparator"`

	// An array of decimal values representing all segments of a version, ordered from most to least significant. How a version string is rendered into a list of decimals will vary depending on the format of the source string and is therefore left up to the caller, but it must be done consistently across all versions of the same resource for sorting to work properly. This is represented as a string to avoid losing precision when converting to a floating point number.
	// Min Length: 1
	SortableVersion []string `json:"sortable_version"`

	// The required version in its original form.
	// Min Length: 1
	Version *string `json:"version,omitempty"`
}

// Validate validates this v1 sub schema requirements items
func (m *V1SubSchemaRequirementsItems) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateComparator(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSortableVersion(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var v1SubSchemaRequirementsItemsTypeComparatorPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["eq","gt","gte","lt","lte","ne"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		v1SubSchemaRequirementsItemsTypeComparatorPropEnum = append(v1SubSchemaRequirementsItemsTypeComparatorPropEnum, v)
	}
}

const (

	// V1SubSchemaRequirementsItemsComparatorEq captures enum value "eq"
	V1SubSchemaRequirementsItemsComparatorEq string = "eq"

	// V1SubSchemaRequirementsItemsComparatorGt captures enum value "gt"
	V1SubSchemaRequirementsItemsComparatorGt string = "gt"

	// V1SubSchemaRequirementsItemsComparatorGte captures enum value "gte"
	V1SubSchemaRequirementsItemsComparatorGte string = "gte"

	// V1SubSchemaRequirementsItemsComparatorLt captures enum value "lt"
	V1SubSchemaRequirementsItemsComparatorLt string = "lt"

	// V1SubSchemaRequirementsItemsComparatorLte captures enum value "lte"
	V1SubSchemaRequirementsItemsComparatorLte string = "lte"

	// V1SubSchemaRequirementsItemsComparatorNe captures enum value "ne"
	V1SubSchemaRequirementsItemsComparatorNe string = "ne"
)

// prop value enum
func (m *V1SubSchemaRequirementsItems) validateComparatorEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, v1SubSchemaRequirementsItemsTypeComparatorPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *V1SubSchemaRequirementsItems) validateComparator(formats strfmt.Registry) error {

	if err := validate.Required("comparator", "body", m.Comparator); err != nil {
		return err
	}

	// value enum
	if err := m.validateComparatorEnum("comparator", "body", *m.Comparator); err != nil {
		return err
	}

	return nil
}

func (m *V1SubSchemaRequirementsItems) validateSortableVersion(formats strfmt.Registry) error {

	if swag.IsZero(m.SortableVersion) { // not required
		return nil
	}

	for i := 0; i < len(m.SortableVersion); i++ {

		if err := validate.MinLength("sortable_version"+"."+strconv.Itoa(i), "body", string(m.SortableVersion[i]), 1); err != nil {
			return err
		}

	}

	return nil
}

func (m *V1SubSchemaRequirementsItems) validateVersion(formats strfmt.Registry) error {

	if swag.IsZero(m.Version) { // not required
		return nil
	}

	if err := validate.MinLength("version", "body", string(*m.Version), 1); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1SubSchemaRequirementsItems) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1SubSchemaRequirementsItems) UnmarshalBinary(b []byte) error {
	var res V1SubSchemaRequirementsItems
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
