#! /usr/bin/env bash

if [[ "$(cat /proc/sys/kernel/perf_event_paranoid)" != "1" ]]; then
	sudo sh -c 'echo 1 >/proc/sys/kernel/perf_event_paranoid'
fi

bins=(
  "./go-hello/build/go-hello"
  "./go-hello/build/go-hello-packed"
  "./rust-hello/build/rust-hello"
  "./rust-hello/build/rust-hello-packed"
  "./zig-hello/build/zig-hello"
)

for bin in ${bins[@]}; do
  echo "--- --- ---"
  ls -lahs ${bin%% *} | cut -d" " -f1,10
  perf stat -r 100 -B ${bin} >/dev/null
done
