// Code generated by go-swagger; DO NOT EDIT.

package inventory_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IngredientOption Ingredient Option
//
// Parameters to the build of this ingredient that should be applied if the conditions are met. Must specify either command line args, resource requirements, or both.
//
// swagger:model ingredientOption
type IngredientOption struct {

	// Command-line arguments to append to the builder invocation
	// Min Items: 1
	CommandLineArgs []string `json:"command_line_args"`

	// At least one condition set from this list must be satisfied for this ingredient option to be applied in a recipe (i.e condition sets are ORed together)
	ConditionSets []*IngredientOptionConditionSet `json:"condition_sets"`

	// resources
	Resources *IngredientOptionResources `json:"resources,omitempty"`
}

// Validate validates this ingredient option
func (m *IngredientOption) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCommandLineArgs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateConditionSets(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateResources(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IngredientOption) validateCommandLineArgs(formats strfmt.Registry) error {

	if swag.IsZero(m.CommandLineArgs) { // not required
		return nil
	}

	iCommandLineArgsSize := int64(len(m.CommandLineArgs))

	if err := validate.MinItems("command_line_args", "body", iCommandLineArgsSize, 1); err != nil {
		return err
	}

	for i := 0; i < len(m.CommandLineArgs); i++ {

		if err := validate.MinLength("command_line_args"+"."+strconv.Itoa(i), "body", string(m.CommandLineArgs[i]), 1); err != nil {
			return err
		}

	}

	return nil
}

func (m *IngredientOption) validateConditionSets(formats strfmt.Registry) error {

	if swag.IsZero(m.ConditionSets) { // not required
		return nil
	}

	for i := 0; i < len(m.ConditionSets); i++ {
		if swag.IsZero(m.ConditionSets[i]) { // not required
			continue
		}

		if m.ConditionSets[i] != nil {
			if err := m.ConditionSets[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("condition_sets" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *IngredientOption) validateResources(formats strfmt.Registry) error {

	if swag.IsZero(m.Resources) { // not required
		return nil
	}

	if m.Resources != nil {
		if err := m.Resources.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("resources")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *IngredientOption) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IngredientOption) UnmarshalBinary(b []byte) error {
	var res IngredientOption
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
