// Code generated by go-swagger; DO NOT EDIT.

package inventory_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IngredientOptionSetRevisionCore Ingredient Option Set Revision Core
//
// The properties of an ingredient option set revision needed to create a new one
//
// swagger:model ingredientOptionSetRevisionCore
type IngredientOptionSetRevisionCore struct {
	IngredientOptionSetRevisionCoreAllOf0

	RevisionBase
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *IngredientOptionSetRevisionCore) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 IngredientOptionSetRevisionCoreAllOf0
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.IngredientOptionSetRevisionCoreAllOf0 = aO0

	// AO1
	var aO1 RevisionBase
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.RevisionBase = aO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m IngredientOptionSetRevisionCore) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.IngredientOptionSetRevisionCoreAllOf0)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.RevisionBase)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this ingredient option set revision core
func (m *IngredientOptionSetRevisionCore) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with IngredientOptionSetRevisionCoreAllOf0
	if err := m.IngredientOptionSetRevisionCoreAllOf0.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with RevisionBase
	if err := m.RevisionBase.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this ingredient option set revision core based on the context it is used
func (m *IngredientOptionSetRevisionCore) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with IngredientOptionSetRevisionCoreAllOf0
	if err := m.IngredientOptionSetRevisionCoreAllOf0.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with RevisionBase
	if err := m.RevisionBase.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *IngredientOptionSetRevisionCore) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IngredientOptionSetRevisionCore) UnmarshalBinary(b []byte) error {
	var res IngredientOptionSetRevisionCore
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
