// Code generated by go-swagger; DO NOT EDIT.

package inventory_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SolverValidationError Solver Validation Error
//
// An error for when invalid input is supplied to a solver endpoint.
//
// swagger:model solverValidationError
type SolverValidationError struct {
	SolverError

	SolverRemediableError

	SolverValidationErrorAllOf2
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *SolverValidationError) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 SolverError
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.SolverError = aO0

	// AO1
	var aO1 SolverRemediableError
	if err := swag.ReadJSON(raw, &aO1); err != nil {
		return err
	}
	m.SolverRemediableError = aO1

	// AO2
	var aO2 SolverValidationErrorAllOf2
	if err := swag.ReadJSON(raw, &aO2); err != nil {
		return err
	}
	m.SolverValidationErrorAllOf2 = aO2

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m SolverValidationError) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 3)

	aO0, err := swag.WriteJSON(m.SolverError)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	aO1, err := swag.WriteJSON(m.SolverRemediableError)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO1)

	aO2, err := swag.WriteJSON(m.SolverValidationErrorAllOf2)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO2)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this solver validation error
func (m *SolverValidationError) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with SolverError
	if err := m.SolverError.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with SolverRemediableError
	if err := m.SolverRemediableError.Validate(formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with SolverValidationErrorAllOf2
	if err := m.SolverValidationErrorAllOf2.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validate this solver validation error based on the context it is used
func (m *SolverValidationError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with SolverError
	if err := m.SolverError.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with SolverRemediableError
	if err := m.SolverRemediableError.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}
	// validation for a type composition with SolverValidationErrorAllOf2
	if err := m.SolverValidationErrorAllOf2.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *SolverValidationError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SolverValidationError) UnmarshalBinary(b []byte) error {
	var res SolverValidationError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
