// Code generated by go-swagger; DO NOT EDIT.

package inventory_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// V1KernelPagedList Kernel Paged List
//
// A paginated list of kernels
// swagger:model v1KernelPagedList
type V1KernelPagedList struct {

	// A page of kernels
	// Required: true
	Kernels []*V1KernelPagedListKernelsItems `json:"kernels"`

	// links
	// Required: true
	Links *V1KernelPagedListLinks `json:"links"`

	// paging
	// Required: true
	Paging *V1KernelPagedListPaging `json:"paging"`
}

// Validate validates this v1 kernel paged list
func (m *V1KernelPagedList) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateKernels(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePaging(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *V1KernelPagedList) validateKernels(formats strfmt.Registry) error {

	if err := validate.Required("kernels", "body", m.Kernels); err != nil {
		return err
	}

	for i := 0; i < len(m.Kernels); i++ {
		if swag.IsZero(m.Kernels[i]) { // not required
			continue
		}

		if m.Kernels[i] != nil {
			if err := m.Kernels[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("kernels" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *V1KernelPagedList) validateLinks(formats strfmt.Registry) error {

	if err := validate.Required("links", "body", m.Links); err != nil {
		return err
	}

	if m.Links != nil {
		if err := m.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("links")
			}
			return err
		}
	}

	return nil
}

func (m *V1KernelPagedList) validatePaging(formats strfmt.Registry) error {

	if err := validate.Required("paging", "body", m.Paging); err != nil {
		return err
	}

	if m.Paging != nil {
		if err := m.Paging.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("paging")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *V1KernelPagedList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *V1KernelPagedList) UnmarshalBinary(b []byte) error {
	var res V1KernelPagedList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
