// Code generated by go-swagger; DO NOT EDIT.

package inventory_models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// VersionRequirement Version Requirement
//
// The version constraint for a feature
//
// swagger:model versionRequirement
type VersionRequirement struct {

	// The operator used to compare the version against a given provided feature to determine if it meets this requirement
	// Required: true
	// Enum: [eq gt gte lt lte ne]
	Comparator *string `json:"comparator"`

	// The required version in its original form
	// Required: true
	// Min Length: 1
	Version *string `json:"version"`
}

// Validate validates this version requirement
func (m *VersionRequirement) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateComparator(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var versionRequirementTypeComparatorPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["eq","gt","gte","lt","lte","ne"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		versionRequirementTypeComparatorPropEnum = append(versionRequirementTypeComparatorPropEnum, v)
	}
}

const (

	// VersionRequirementComparatorEq captures enum value "eq"
	VersionRequirementComparatorEq string = "eq"

	// VersionRequirementComparatorGt captures enum value "gt"
	VersionRequirementComparatorGt string = "gt"

	// VersionRequirementComparatorGte captures enum value "gte"
	VersionRequirementComparatorGte string = "gte"

	// VersionRequirementComparatorLt captures enum value "lt"
	VersionRequirementComparatorLt string = "lt"

	// VersionRequirementComparatorLte captures enum value "lte"
	VersionRequirementComparatorLte string = "lte"

	// VersionRequirementComparatorNe captures enum value "ne"
	VersionRequirementComparatorNe string = "ne"
)

// prop value enum
func (m *VersionRequirement) validateComparatorEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, versionRequirementTypeComparatorPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *VersionRequirement) validateComparator(formats strfmt.Registry) error {

	if err := validate.Required("comparator", "body", m.Comparator); err != nil {
		return err
	}

	// value enum
	if err := m.validateComparatorEnum("comparator", "body", *m.Comparator); err != nil {
		return err
	}

	return nil
}

func (m *VersionRequirement) validateVersion(formats strfmt.Registry) error {

	if err := validate.Required("version", "body", m.Version); err != nil {
		return err
	}

	if err := validate.MinLength("version", "body", string(*m.Version), 1); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *VersionRequirement) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VersionRequirement) UnmarshalBinary(b []byte) error {
	var res VersionRequirement
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
