version: '3.8'

services:
  state-installer-test:
    build:
      context: ..
      dockerfile: docker-test/Dockerfile
    container_name: state-installer-test
    hostname: state-installer-test
    network_mode: bridge
    volumes:
      # Mount a volume for persistent logs and test results
      - ./test-results:/opt/state-test/test-results
      # Mount the build directory for easy updates
      - ../build:/opt/state-test/build:ro
    environment:
      # Environment variables for testing
      - VERBOSE=true
      - TERM=xterm-256color
      # You can override these to test different configurations
      - CONFIG_FLAGS=--config-set analytics.enabled=false --config-set output.level=debug
      - INSTALL_PATH=/opt/state-install
      - INSTALLER_FLAGS=--force --non-interactive
    ports:
      # Expose ports for network monitoring if needed
      - "8080:8080"
    stdin_open: true
    tty: true
    # Keep container running for interactive testing
    command: ["/bin/bash", "-c", "while true; do sleep 30; done"]
    # Add capabilities for network monitoring
    cap_add:
      - NET_ADMIN
      - NET_RAW
    # Security options for network monitoring
    security_opt:
      - seccomp:unconfined

  # Optional: Add a network monitoring service
  network-monitor:
    image: nicolaka/netshoot
    container_name: state-network-monitor
    network_mode: "container:state-installer-test"
    depends_on:
      - state-installer-test
    command: ["sleep", "infinity"]
    profiles:
      - monitoring

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
