// Code generated by go-swagger; DO NOT EDIT.

package components

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewListComponentsParams creates a new ListComponentsParams object
// with the default values initialized.
func NewListComponentsParams() *ListComponentsParams {
	var ()
	return &ListComponentsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListComponentsParamsWithTimeout creates a new ListComponentsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListComponentsParamsWithTimeout(timeout time.Duration) *ListComponentsParams {
	var ()
	return &ListComponentsParams{

		timeout: timeout,
	}
}

// NewListComponentsParamsWithContext creates a new ListComponentsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListComponentsParamsWithContext(ctx context.Context) *ListComponentsParams {
	var ()
	return &ListComponentsParams{

		Context: ctx,
	}
}

// NewListComponentsParamsWithHTTPClient creates a new ListComponentsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListComponentsParamsWithHTTPClient(client *http.Client) *ListComponentsParams {
	var ()
	return &ListComponentsParams{
		HTTPClient: client,
	}
}

/*ListComponentsParams contains all the parameters to send to the API endpoint
for the list components operation typically these are written to a http.Request
*/
type ListComponentsParams struct {

	/*Cid
	  All components for CID

	*/
	Cid *strfmt.UUID
	/*NameFilter
	  Match component names based on this regexp

	*/
	NameFilter *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list components params
func (o *ListComponentsParams) WithTimeout(timeout time.Duration) *ListComponentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list components params
func (o *ListComponentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list components params
func (o *ListComponentsParams) WithContext(ctx context.Context) *ListComponentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list components params
func (o *ListComponentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list components params
func (o *ListComponentsParams) WithHTTPClient(client *http.Client) *ListComponentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list components params
func (o *ListComponentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCid adds the cid to the list components params
func (o *ListComponentsParams) WithCid(cid *strfmt.UUID) *ListComponentsParams {
	o.SetCid(cid)
	return o
}

// SetCid adds the cid to the list components params
func (o *ListComponentsParams) SetCid(cid *strfmt.UUID) {
	o.Cid = cid
}

// WithNameFilter adds the nameFilter to the list components params
func (o *ListComponentsParams) WithNameFilter(nameFilter *string) *ListComponentsParams {
	o.SetNameFilter(nameFilter)
	return o
}

// SetNameFilter adds the nameFilter to the list components params
func (o *ListComponentsParams) SetNameFilter(nameFilter *string) {
	o.NameFilter = nameFilter
}

// WriteToRequest writes these params to a swagger request
func (o *ListComponentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Cid != nil {

		// query param cid
		var qrCid strfmt.UUID
		if o.Cid != nil {
			qrCid = *o.Cid
		}
		qCid := qrCid.String()
		if qCid != "" {
			if err := r.SetQueryParam("cid", qCid); err != nil {
				return err
			}
		}

	}

	if o.NameFilter != nil {

		// query param nameFilter
		var qrNameFilter string
		if o.NameFilter != nil {
			qrNameFilter = *o.NameFilter
		}
		qNameFilter := qrNameFilter
		if qNameFilter != "" {
			if err := r.SetQueryParam("nameFilter", qNameFilter); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
