// Code generated by go-swagger; DO NOT EDIT.

package secrets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	secrets_models "github.com/ActiveState/cli/pkg/platform/api/secrets/secrets_models"
)

// SaveDefinitionReader is a Reader for the SaveDefinition structure.
type SaveDefinitionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SaveDefinitionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewSaveDefinitionNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewSaveDefinitionUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewSaveDefinitionInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewSaveDefinitionNoContent creates a SaveDefinitionNoContent with default headers values
func NewSaveDefinitionNoContent() *SaveDefinitionNoContent {
	return &SaveDefinitionNoContent{}
}

/*
SaveDefinitionNoContent handles this case with default header values.

Success
*/
type SaveDefinitionNoContent struct {
}

func (o *SaveDefinitionNoContent) Error() string {
	return fmt.Sprintf("[PUT /definitions/{projectID}][%d] saveDefinitionNoContent ", 204)
}

func (o *SaveDefinitionNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSaveDefinitionUnauthorized creates a SaveDefinitionUnauthorized with default headers values
func NewSaveDefinitionUnauthorized() *SaveDefinitionUnauthorized {
	return &SaveDefinitionUnauthorized{}
}

/*
SaveDefinitionUnauthorized handles this case with default header values.

Invalid credentials
*/
type SaveDefinitionUnauthorized struct {
	Payload *secrets_models.Message
}

func (o *SaveDefinitionUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /definitions/{projectID}][%d] saveDefinitionUnauthorized  %+v", 401, o.Payload)
}

func (o *SaveDefinitionUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(secrets_models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSaveDefinitionInternalServerError creates a SaveDefinitionInternalServerError with default headers values
func NewSaveDefinitionInternalServerError() *SaveDefinitionInternalServerError {
	return &SaveDefinitionInternalServerError{}
}

/*
SaveDefinitionInternalServerError handles this case with default header values.

Server Error
*/
type SaveDefinitionInternalServerError struct {
	Payload *secrets_models.Message
}

func (o *SaveDefinitionInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /definitions/{projectID}][%d] saveDefinitionInternalServerError  %+v", 500, o.Payload)
}

func (o *SaveDefinitionInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(secrets_models.Message)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
