#! /usr/bin/env bash

if [[ "$(cat /proc/sys/kernel/perf_event_paranoid)" != "1" ]]; then
  sudo sh -c 'echo 1 >/proc/sys/kernel/perf_event_paranoid'
fi

bins=(
  "./go-forward/build/go-forward"
  "./zig-forward/build/zig-forward"
)

sockFile="${1}"
execPython3="${2}"

perf stat -r 100 -B /usr/bin/python3 -c "print('234')" > /dev/null

for bin in ${bins[@]}; do
  echo "--- --- ---"
  ls -lahs ${bin%% *} | cut -d" " -f1,10
  perf stat -r 100 -B ${bin} ${sockFile} -c "print('234')" > /dev/null
done

perf stat -r 100 -B ${execPython3} -c "print('234')" > /dev/null
