#! /usr/bin/env bash

if [[ "$(cat /proc/sys/kernel/perf_event_paranoid)" != "1" ]]; then
  sudo sh -c 'echo 1 >/proc/sys/kernel/perf_event_paranoid'
fi

bins=(
  "./go-forward/build/go-forward"
  "./zig-forward/build/zig-forward"
)

for bin in ${bins[@]}; do
  echo "--- --- ---"
  ls -lahs ${bin%% *} | cut -d" " -f1,10
  perf stat -r 100 -B ${bin} > /dev/null
done
