#! /usr/bin/env bash

function availableCalls() {
	grep "func.*Client) \w*(params.*error) {" ./api/* -r |
		grep -E "(\w|/)*.go:.*\w\(params" -o |
		sed 's/:func (\w* \*Client) /\t/g; s/(params//g' |
		sed 's#^/##g' |
		column -c 2
}

function probableCalls() {
	local func="${1}"
	grep ".*=.*${func}(.*" * -nr | grep ".*.go:\d*:func" -v
}

function main() {
	echo "This is \"best effort\" since it is based on text and not AST analysis."

	local line file func lastFile pkg
	echo "$(availableCalls)" | while read -r line; do
		file="${line%%$'\t'*}"
		func="${line##*$'\t'}"

		if [[ "${file}" != "${lastFile}" ]]; then
			pkg="$(grep "package .*" "${file}" | sed 's/package //g')"
			echo "${file}"
			lastFile="${file}"
		fi

		echo -e "\t${pkg}.Client.${func}"

		local l
		echo "$(probableCalls "${func}")" | while read -r l; do
			[[ -z "${l}" ]] && continue
			echo -e "\t\t${l}"
		done
	done
}

main
