// Code generated by go-swagger; DO NOT EDIT.

package inventory_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/ActiveState/cli/pkg/platform/api/inventory/inventory_models"
)

// NewAddIngredientAndVersionsParams creates a new AddIngredientAndVersionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddIngredientAndVersionsParams() *AddIngredientAndVersionsParams {
	return &AddIngredientAndVersionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddIngredientAndVersionsParamsWithTimeout creates a new AddIngredientAndVersionsParams object
// with the ability to set a timeout on a request.
func NewAddIngredientAndVersionsParamsWithTimeout(timeout time.Duration) *AddIngredientAndVersionsParams {
	return &AddIngredientAndVersionsParams{
		timeout: timeout,
	}
}

// NewAddIngredientAndVersionsParamsWithContext creates a new AddIngredientAndVersionsParams object
// with the ability to set a context for a request.
func NewAddIngredientAndVersionsParamsWithContext(ctx context.Context) *AddIngredientAndVersionsParams {
	return &AddIngredientAndVersionsParams{
		Context: ctx,
	}
}

// NewAddIngredientAndVersionsParamsWithHTTPClient creates a new AddIngredientAndVersionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddIngredientAndVersionsParamsWithHTTPClient(client *http.Client) *AddIngredientAndVersionsParams {
	return &AddIngredientAndVersionsParams{
		HTTPClient: client,
	}
}

/* AddIngredientAndVersionsParams contains all the parameters to send to the API endpoint
   for the add ingredient and versions operation.

   Typically these are written to a http.Request.
*/
type AddIngredientAndVersionsParams struct {

	/* DisableSmartImport.

	   Disables the smart-import feature for this import
	*/
	DisableSmartImport *bool

	// IngredientAndVersions.
	IngredientAndVersions *inventory_models.IngredientAllInOneCreate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add ingredient and versions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddIngredientAndVersionsParams) WithDefaults() *AddIngredientAndVersionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add ingredient and versions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddIngredientAndVersionsParams) SetDefaults() {
	var (
		disableSmartImportDefault = bool(false)
	)

	val := AddIngredientAndVersionsParams{
		DisableSmartImport: &disableSmartImportDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the add ingredient and versions params
func (o *AddIngredientAndVersionsParams) WithTimeout(timeout time.Duration) *AddIngredientAndVersionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add ingredient and versions params
func (o *AddIngredientAndVersionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add ingredient and versions params
func (o *AddIngredientAndVersionsParams) WithContext(ctx context.Context) *AddIngredientAndVersionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add ingredient and versions params
func (o *AddIngredientAndVersionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add ingredient and versions params
func (o *AddIngredientAndVersionsParams) WithHTTPClient(client *http.Client) *AddIngredientAndVersionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add ingredient and versions params
func (o *AddIngredientAndVersionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithDisableSmartImport adds the disableSmartImport to the add ingredient and versions params
func (o *AddIngredientAndVersionsParams) WithDisableSmartImport(disableSmartImport *bool) *AddIngredientAndVersionsParams {
	o.SetDisableSmartImport(disableSmartImport)
	return o
}

// SetDisableSmartImport adds the disableSmartImport to the add ingredient and versions params
func (o *AddIngredientAndVersionsParams) SetDisableSmartImport(disableSmartImport *bool) {
	o.DisableSmartImport = disableSmartImport
}

// WithIngredientAndVersions adds the ingredientAndVersions to the add ingredient and versions params
func (o *AddIngredientAndVersionsParams) WithIngredientAndVersions(ingredientAndVersions *inventory_models.IngredientAllInOneCreate) *AddIngredientAndVersionsParams {
	o.SetIngredientAndVersions(ingredientAndVersions)
	return o
}

// SetIngredientAndVersions adds the ingredientAndVersions to the add ingredient and versions params
func (o *AddIngredientAndVersionsParams) SetIngredientAndVersions(ingredientAndVersions *inventory_models.IngredientAllInOneCreate) {
	o.IngredientAndVersions = ingredientAndVersions
}

// WriteToRequest writes these params to a swagger request
func (o *AddIngredientAndVersionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.DisableSmartImport != nil {

		// query param disable_smart_import
		var qrDisableSmartImport bool

		if o.DisableSmartImport != nil {
			qrDisableSmartImport = *o.DisableSmartImport
		}
		qDisableSmartImport := swag.FormatBool(qrDisableSmartImport)
		if qDisableSmartImport != "" {

			if err := r.SetQueryParam("disable_smart_import", qDisableSmartImport); err != nil {
				return err
			}
		}
	}
	if o.IngredientAndVersions != nil {
		if err := r.SetBodyParam(o.IngredientAndVersions); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
