// Code generated by go-swagger; DO NOT EDIT.

package inventory_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ActiveState/cli/pkg/platform/api/inventory/inventory_models"
)

// NewAddOperatingSystemParams creates a new AddOperatingSystemParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAddOperatingSystemParams() *AddOperatingSystemParams {
	return &AddOperatingSystemParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAddOperatingSystemParamsWithTimeout creates a new AddOperatingSystemParams object
// with the ability to set a timeout on a request.
func NewAddOperatingSystemParamsWithTimeout(timeout time.Duration) *AddOperatingSystemParams {
	return &AddOperatingSystemParams{
		timeout: timeout,
	}
}

// NewAddOperatingSystemParamsWithContext creates a new AddOperatingSystemParams object
// with the ability to set a context for a request.
func NewAddOperatingSystemParamsWithContext(ctx context.Context) *AddOperatingSystemParams {
	return &AddOperatingSystemParams{
		Context: ctx,
	}
}

// NewAddOperatingSystemParamsWithHTTPClient creates a new AddOperatingSystemParams object
// with the ability to set a custom HTTPClient for a request.
func NewAddOperatingSystemParamsWithHTTPClient(client *http.Client) *AddOperatingSystemParams {
	return &AddOperatingSystemParams{
		HTTPClient: client,
	}
}

/* AddOperatingSystemParams contains all the parameters to send to the API endpoint
   for the add operating system operation.

   Typically these are written to a http.Request.
*/
type AddOperatingSystemParams struct {

	// OperatingSystem.
	OperatingSystem *inventory_models.OperatingSystemCore

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the add operating system params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddOperatingSystemParams) WithDefaults() *AddOperatingSystemParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the add operating system params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AddOperatingSystemParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the add operating system params
func (o *AddOperatingSystemParams) WithTimeout(timeout time.Duration) *AddOperatingSystemParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the add operating system params
func (o *AddOperatingSystemParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the add operating system params
func (o *AddOperatingSystemParams) WithContext(ctx context.Context) *AddOperatingSystemParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the add operating system params
func (o *AddOperatingSystemParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the add operating system params
func (o *AddOperatingSystemParams) WithHTTPClient(client *http.Client) *AddOperatingSystemParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the add operating system params
func (o *AddOperatingSystemParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOperatingSystem adds the operatingSystem to the add operating system params
func (o *AddOperatingSystemParams) WithOperatingSystem(operatingSystem *inventory_models.OperatingSystemCore) *AddOperatingSystemParams {
	o.SetOperatingSystem(operatingSystem)
	return o
}

// SetOperatingSystem adds the operatingSystem to the add operating system params
func (o *AddOperatingSystemParams) SetOperatingSystem(operatingSystem *inventory_models.OperatingSystemCore) {
	o.OperatingSystem = operatingSystem
}

// WriteToRequest writes these params to a swagger request
func (o *AddOperatingSystemParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.OperatingSystem != nil {
		if err := r.SetBodyParam(o.OperatingSystem); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
