// Code generated by go-swagger; DO NOT EDIT.

package inventory_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetLibcsParams creates a new GetLibcsParams object
// with the default values initialized.
func NewGetLibcsParams() *GetLibcsParams {
	var (
		limitDefault = int64(50)
		pageDefault  = int64(1)
	)
	return &GetLibcsParams{
		Limit: &limitDefault,
		Page:  &pageDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetLibcsParamsWithTimeout creates a new GetLibcsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetLibcsParamsWithTimeout(timeout time.Duration) *GetLibcsParams {
	var (
		limitDefault = int64(50)
		pageDefault  = int64(1)
	)
	return &GetLibcsParams{
		Limit: &limitDefault,
		Page:  &pageDefault,

		timeout: timeout,
	}
}

// NewGetLibcsParamsWithContext creates a new GetLibcsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetLibcsParamsWithContext(ctx context.Context) *GetLibcsParams {
	var (
		limitDefault = int64(50)
		pageDefault  = int64(1)
	)
	return &GetLibcsParams{
		Limit: &limitDefault,
		Page:  &pageDefault,

		Context: ctx,
	}
}

// NewGetLibcsParamsWithHTTPClient creates a new GetLibcsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetLibcsParamsWithHTTPClient(client *http.Client) *GetLibcsParams {
	var (
		limitDefault = int64(50)
		pageDefault  = int64(1)
	)
	return &GetLibcsParams{
		Limit:      &limitDefault,
		Page:       &pageDefault,
		HTTPClient: client,
	}
}

/*GetLibcsParams contains all the parameters to send to the API endpoint
for the get libcs operation typically these are written to a http.Request
*/
type GetLibcsParams struct {

	/*Limit
	  The maximum number of items returned per page

	*/
	Limit *int64
	/*Page
	  The page number returned

	*/
	Page *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get libcs params
func (o *GetLibcsParams) WithTimeout(timeout time.Duration) *GetLibcsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get libcs params
func (o *GetLibcsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get libcs params
func (o *GetLibcsParams) WithContext(ctx context.Context) *GetLibcsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get libcs params
func (o *GetLibcsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get libcs params
func (o *GetLibcsParams) WithHTTPClient(client *http.Client) *GetLibcsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get libcs params
func (o *GetLibcsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get libcs params
func (o *GetLibcsParams) WithLimit(limit *int64) *GetLibcsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get libcs params
func (o *GetLibcsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithPage adds the page to the get libcs params
func (o *GetLibcsParams) WithPage(page *int64) *GetLibcsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get libcs params
func (o *GetLibcsParams) SetPage(page *int64) {
	o.Page = page
}

// WriteToRequest writes these params to a swagger request
func (o *GetLibcsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Page != nil {

		// query param page
		var qrPage int64
		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {
			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
