// Code generated by go-swagger; DO NOT EDIT.

package inventory_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetLibcVersionParams creates a new GetLibcVersionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetLibcVersionParams() *GetLibcVersionParams {
	return &GetLibcVersionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetLibcVersionParamsWithTimeout creates a new GetLibcVersionParams object
// with the ability to set a timeout on a request.
func NewGetLibcVersionParamsWithTimeout(timeout time.Duration) *GetLibcVersionParams {
	return &GetLibcVersionParams{
		timeout: timeout,
	}
}

// NewGetLibcVersionParamsWithContext creates a new GetLibcVersionParams object
// with the ability to set a context for a request.
func NewGetLibcVersionParamsWithContext(ctx context.Context) *GetLibcVersionParams {
	return &GetLibcVersionParams{
		Context: ctx,
	}
}

// NewGetLibcVersionParamsWithHTTPClient creates a new GetLibcVersionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetLibcVersionParamsWithHTTPClient(client *http.Client) *GetLibcVersionParams {
	return &GetLibcVersionParams{
		HTTPClient: client,
	}
}

/* GetLibcVersionParams contains all the parameters to send to the API endpoint
   for the get libc version operation.

   Typically these are written to a http.Request.
*/
type GetLibcVersionParams struct {

	/* AllowUnstable.

	   Whether to show an unstable revision of a resource if there is an available unstable version newer than the newest available stable version
	*/
	AllowUnstable *bool

	// LibcID.
	//
	// Format: uuid
	LibcID strfmt.UUID

	// LibcVersionID.
	//
	// Format: uuid
	LibcVersionID strfmt.UUID

	/* StateAt.

	   Show the state of a resource as it was at the specified timestamp. If omitted, shows the current state of the resource.

	   Format: date-time
	*/
	StateAt *strfmt.DateTime

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get libc version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLibcVersionParams) WithDefaults() *GetLibcVersionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get libc version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetLibcVersionParams) SetDefaults() {
	var (
		allowUnstableDefault = bool(false)
	)

	val := GetLibcVersionParams{
		AllowUnstable: &allowUnstableDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get libc version params
func (o *GetLibcVersionParams) WithTimeout(timeout time.Duration) *GetLibcVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get libc version params
func (o *GetLibcVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get libc version params
func (o *GetLibcVersionParams) WithContext(ctx context.Context) *GetLibcVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get libc version params
func (o *GetLibcVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get libc version params
func (o *GetLibcVersionParams) WithHTTPClient(client *http.Client) *GetLibcVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get libc version params
func (o *GetLibcVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAllowUnstable adds the allowUnstable to the get libc version params
func (o *GetLibcVersionParams) WithAllowUnstable(allowUnstable *bool) *GetLibcVersionParams {
	o.SetAllowUnstable(allowUnstable)
	return o
}

// SetAllowUnstable adds the allowUnstable to the get libc version params
func (o *GetLibcVersionParams) SetAllowUnstable(allowUnstable *bool) {
	o.AllowUnstable = allowUnstable
}

// WithLibcID adds the libcID to the get libc version params
func (o *GetLibcVersionParams) WithLibcID(libcID strfmt.UUID) *GetLibcVersionParams {
	o.SetLibcID(libcID)
	return o
}

// SetLibcID adds the libcId to the get libc version params
func (o *GetLibcVersionParams) SetLibcID(libcID strfmt.UUID) {
	o.LibcID = libcID
}

// WithLibcVersionID adds the libcVersionID to the get libc version params
func (o *GetLibcVersionParams) WithLibcVersionID(libcVersionID strfmt.UUID) *GetLibcVersionParams {
	o.SetLibcVersionID(libcVersionID)
	return o
}

// SetLibcVersionID adds the libcVersionId to the get libc version params
func (o *GetLibcVersionParams) SetLibcVersionID(libcVersionID strfmt.UUID) {
	o.LibcVersionID = libcVersionID
}

// WithStateAt adds the stateAt to the get libc version params
func (o *GetLibcVersionParams) WithStateAt(stateAt *strfmt.DateTime) *GetLibcVersionParams {
	o.SetStateAt(stateAt)
	return o
}

// SetStateAt adds the stateAt to the get libc version params
func (o *GetLibcVersionParams) SetStateAt(stateAt *strfmt.DateTime) {
	o.StateAt = stateAt
}

// WriteToRequest writes these params to a swagger request
func (o *GetLibcVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AllowUnstable != nil {

		// query param allow_unstable
		var qrAllowUnstable bool

		if o.AllowUnstable != nil {
			qrAllowUnstable = *o.AllowUnstable
		}
		qAllowUnstable := swag.FormatBool(qrAllowUnstable)
		if qAllowUnstable != "" {

			if err := r.SetQueryParam("allow_unstable", qAllowUnstable); err != nil {
				return err
			}
		}
	}

	// path param libc_id
	if err := r.SetPathParam("libc_id", o.LibcID.String()); err != nil {
		return err
	}

	// path param libc_version_id
	if err := r.SetPathParam("libc_version_id", o.LibcVersionID.String()); err != nil {
		return err
	}

	if o.StateAt != nil {

		// query param state_at
		var qrStateAt strfmt.DateTime

		if o.StateAt != nil {
			qrStateAt = *o.StateAt
		}
		qStateAt := qrStateAt.String()
		if qStateAt != "" {

			if err := r.SetQueryParam("state_at", qStateAt); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
