// Code generated by go-swagger; DO NOT EDIT.

package inventory_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetNamespaceIngredientVersionsParams creates a new GetNamespaceIngredientVersionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetNamespaceIngredientVersionsParams() *GetNamespaceIngredientVersionsParams {
	return &GetNamespaceIngredientVersionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetNamespaceIngredientVersionsParamsWithTimeout creates a new GetNamespaceIngredientVersionsParams object
// with the ability to set a timeout on a request.
func NewGetNamespaceIngredientVersionsParamsWithTimeout(timeout time.Duration) *GetNamespaceIngredientVersionsParams {
	return &GetNamespaceIngredientVersionsParams{
		timeout: timeout,
	}
}

// NewGetNamespaceIngredientVersionsParamsWithContext creates a new GetNamespaceIngredientVersionsParams object
// with the ability to set a context for a request.
func NewGetNamespaceIngredientVersionsParamsWithContext(ctx context.Context) *GetNamespaceIngredientVersionsParams {
	return &GetNamespaceIngredientVersionsParams{
		Context: ctx,
	}
}

// NewGetNamespaceIngredientVersionsParamsWithHTTPClient creates a new GetNamespaceIngredientVersionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetNamespaceIngredientVersionsParamsWithHTTPClient(client *http.Client) *GetNamespaceIngredientVersionsParams {
	return &GetNamespaceIngredientVersionsParams{
		HTTPClient: client,
	}
}

/* GetNamespaceIngredientVersionsParams contains all the parameters to send to the API endpoint
   for the get namespace ingredient versions operation.

   Typically these are written to a http.Request.
*/
type GetNamespaceIngredientVersionsParams struct {

	/* AllowUnstable.

	   Whether to show an unstable revision of a resource if there is an available unstable version newer than the newest available stable version
	*/
	AllowUnstable *bool

	/* Limit.

	   The maximum number of items returned per page

	   Default: 50
	*/
	Limit *int64

	// Name.
	Name string

	// Namespace.
	Namespace string

	/* Page.

	   The page number returned

	   Default: 1
	*/
	Page *int64

	/* StateAt.

	   Show the state of a resource as it was at the specified timestamp. If omitted, shows the current state of the resource.

	   Format: date-time
	*/
	StateAt *strfmt.DateTime

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get namespace ingredient versions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNamespaceIngredientVersionsParams) WithDefaults() *GetNamespaceIngredientVersionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get namespace ingredient versions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetNamespaceIngredientVersionsParams) SetDefaults() {
	var (
		allowUnstableDefault = bool(false)

		limitDefault = int64(50)

		pageDefault = int64(1)
	)

	val := GetNamespaceIngredientVersionsParams{
		AllowUnstable: &allowUnstableDefault,
		Limit:         &limitDefault,
		Page:          &pageDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get namespace ingredient versions params
func (o *GetNamespaceIngredientVersionsParams) WithTimeout(timeout time.Duration) *GetNamespaceIngredientVersionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get namespace ingredient versions params
func (o *GetNamespaceIngredientVersionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get namespace ingredient versions params
func (o *GetNamespaceIngredientVersionsParams) WithContext(ctx context.Context) *GetNamespaceIngredientVersionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get namespace ingredient versions params
func (o *GetNamespaceIngredientVersionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get namespace ingredient versions params
func (o *GetNamespaceIngredientVersionsParams) WithHTTPClient(client *http.Client) *GetNamespaceIngredientVersionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get namespace ingredient versions params
func (o *GetNamespaceIngredientVersionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAllowUnstable adds the allowUnstable to the get namespace ingredient versions params
func (o *GetNamespaceIngredientVersionsParams) WithAllowUnstable(allowUnstable *bool) *GetNamespaceIngredientVersionsParams {
	o.SetAllowUnstable(allowUnstable)
	return o
}

// SetAllowUnstable adds the allowUnstable to the get namespace ingredient versions params
func (o *GetNamespaceIngredientVersionsParams) SetAllowUnstable(allowUnstable *bool) {
	o.AllowUnstable = allowUnstable
}

// WithLimit adds the limit to the get namespace ingredient versions params
func (o *GetNamespaceIngredientVersionsParams) WithLimit(limit *int64) *GetNamespaceIngredientVersionsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get namespace ingredient versions params
func (o *GetNamespaceIngredientVersionsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithName adds the name to the get namespace ingredient versions params
func (o *GetNamespaceIngredientVersionsParams) WithName(name string) *GetNamespaceIngredientVersionsParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get namespace ingredient versions params
func (o *GetNamespaceIngredientVersionsParams) SetName(name string) {
	o.Name = name
}

// WithNamespace adds the namespace to the get namespace ingredient versions params
func (o *GetNamespaceIngredientVersionsParams) WithNamespace(namespace string) *GetNamespaceIngredientVersionsParams {
	o.SetNamespace(namespace)
	return o
}

// SetNamespace adds the namespace to the get namespace ingredient versions params
func (o *GetNamespaceIngredientVersionsParams) SetNamespace(namespace string) {
	o.Namespace = namespace
}

// WithPage adds the page to the get namespace ingredient versions params
func (o *GetNamespaceIngredientVersionsParams) WithPage(page *int64) *GetNamespaceIngredientVersionsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get namespace ingredient versions params
func (o *GetNamespaceIngredientVersionsParams) SetPage(page *int64) {
	o.Page = page
}

// WithStateAt adds the stateAt to the get namespace ingredient versions params
func (o *GetNamespaceIngredientVersionsParams) WithStateAt(stateAt *strfmt.DateTime) *GetNamespaceIngredientVersionsParams {
	o.SetStateAt(stateAt)
	return o
}

// SetStateAt adds the stateAt to the get namespace ingredient versions params
func (o *GetNamespaceIngredientVersionsParams) SetStateAt(stateAt *strfmt.DateTime) {
	o.StateAt = stateAt
}

// WriteToRequest writes these params to a swagger request
func (o *GetNamespaceIngredientVersionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AllowUnstable != nil {

		// query param allow_unstable
		var qrAllowUnstable bool

		if o.AllowUnstable != nil {
			qrAllowUnstable = *o.AllowUnstable
		}
		qAllowUnstable := swag.FormatBool(qrAllowUnstable)
		if qAllowUnstable != "" {

			if err := r.SetQueryParam("allow_unstable", qAllowUnstable); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	// query param name
	qrName := o.Name
	qName := qrName
	if qName != "" {

		if err := r.SetQueryParam("name", qName); err != nil {
			return err
		}
	}

	// query param namespace
	qrNamespace := o.Namespace
	qNamespace := qrNamespace
	if qNamespace != "" {

		if err := r.SetQueryParam("namespace", qNamespace); err != nil {
			return err
		}
	}

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if o.StateAt != nil {

		// query param state_at
		var qrStateAt strfmt.DateTime

		if o.StateAt != nil {
			qrStateAt = *o.StateAt
		}
		qStateAt := qrStateAt.String()
		if qStateAt != "" {

			if err := r.SetQueryParam("state_at", qStateAt); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
