// Code generated by go-swagger; DO NOT EDIT.

package inventory_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetIngredientsParams creates a new GetIngredientsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetIngredientsParams() *GetIngredientsParams {
	return &GetIngredientsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetIngredientsParamsWithTimeout creates a new GetIngredientsParams object
// with the ability to set a timeout on a request.
func NewGetIngredientsParamsWithTimeout(timeout time.Duration) *GetIngredientsParams {
	return &GetIngredientsParams{
		timeout: timeout,
	}
}

// NewGetIngredientsParamsWithContext creates a new GetIngredientsParams object
// with the ability to set a context for a request.
func NewGetIngredientsParamsWithContext(ctx context.Context) *GetIngredientsParams {
	return &GetIngredientsParams{
		Context: ctx,
	}
}

// NewGetIngredientsParamsWithHTTPClient creates a new GetIngredientsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetIngredientsParamsWithHTTPClient(client *http.Client) *GetIngredientsParams {
	return &GetIngredientsParams{
		HTTPClient: client,
	}
}

/* GetIngredientsParams contains all the parameters to send to the API endpoint
   for the get ingredients operation.

   Typically these are written to a http.Request.
*/
type GetIngredientsParams struct {

	/* Limit.

	   The maximum number of items returned per page

	   Default: 50
	*/
	Limit *int64

	/* Page.

	   The page number returned

	   Default: 1
	*/
	Page *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get ingredients params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIngredientsParams) WithDefaults() *GetIngredientsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get ingredients params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetIngredientsParams) SetDefaults() {
	var (
		limitDefault = int64(50)

		pageDefault = int64(1)
	)

	val := GetIngredientsParams{
		Limit: &limitDefault,
		Page:  &pageDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the get ingredients params
func (o *GetIngredientsParams) WithTimeout(timeout time.Duration) *GetIngredientsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get ingredients params
func (o *GetIngredientsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get ingredients params
func (o *GetIngredientsParams) WithContext(ctx context.Context) *GetIngredientsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get ingredients params
func (o *GetIngredientsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get ingredients params
func (o *GetIngredientsParams) WithHTTPClient(client *http.Client) *GetIngredientsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get ingredients params
func (o *GetIngredientsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get ingredients params
func (o *GetIngredientsParams) WithLimit(limit *int64) *GetIngredientsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get ingredients params
func (o *GetIngredientsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithPage adds the page to the get ingredients params
func (o *GetIngredientsParams) WithPage(page *int64) *GetIngredientsParams {
	o.SetPage(page)
	return o
}

// SetPage adds the page to the get ingredients params
func (o *GetIngredientsParams) SetPage(page *int64) {
	o.Page = page
}

// WriteToRequest writes these params to a swagger request
func (o *GetIngredientsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.Page != nil {

		// query param page
		var qrPage int64

		if o.Page != nil {
			qrPage = *o.Page
		}
		qPage := swag.FormatInt64(qrPage)
		if qPage != "" {

			if err := r.SetQueryParam("page", qPage); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
