// Code generated by go-swagger; DO NOT EDIT.

package inventory_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ActiveState/cli/pkg/platform/api/inventory/inventory_models"
)

// ReadinessCheckReader is a Reader for the ReadinessCheck structure.
type ReadinessCheckReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ReadinessCheckReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewReadinessCheckOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewReadinessCheckDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewReadinessCheckOK creates a ReadinessCheckOK with default headers values
func NewReadinessCheckOK() *ReadinessCheckOK {
	return &ReadinessCheckOK{}
}

/*ReadinessCheckOK handles this case with default header values.

Indicates whether the server is ready
*/
type ReadinessCheckOK struct {
	Payload bool
}

func (o *ReadinessCheckOK) Error() string {
	return fmt.Sprintf("[GET /readiness-check][%d] readinessCheckOK  %+v", 200, o.Payload)
}

func (o *ReadinessCheckOK) GetPayload() bool {
	return o.Payload
}

func (o *ReadinessCheckOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewReadinessCheckDefault creates a ReadinessCheckDefault with default headers values
func NewReadinessCheckDefault(code int) *ReadinessCheckDefault {
	return &ReadinessCheckDefault{
		_statusCode: code,
	}
}

/*ReadinessCheckDefault handles this case with default header values.

generic error response
*/
type ReadinessCheckDefault struct {
	_statusCode int

	Payload *inventory_models.RestAPIError
}

// Code gets the status code for the readiness check default response
func (o *ReadinessCheckDefault) Code() int {
	return o._statusCode
}

func (o *ReadinessCheckDefault) Error() string {
	return fmt.Sprintf("[GET /readiness-check][%d] readinessCheck default  %+v", o._statusCode, o.Payload)
}

func (o *ReadinessCheckDefault) GetPayload() *inventory_models.RestAPIError {
	return o.Payload
}

func (o *ReadinessCheckDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(inventory_models.RestAPIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
