// Code generated by go-swagger; DO NOT EDIT.

package inventory_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	inventory_models "github.com/ActiveState/cli/pkg/platform/api/inventory/inventory_models"
)

// NewSolveOrderParams creates a new SolveOrderParams object
// with the default values initialized.
func NewSolveOrderParams() *SolveOrderParams {
	var (
		returnDevelopmentSolverRecipesDefault = bool(false)
		useRecipeStoreDefault                 = bool(true)
	)
	return &SolveOrderParams{
		ReturnDevelopmentSolverRecipes: &returnDevelopmentSolverRecipesDefault,
		UseRecipeStore:                 &useRecipeStoreDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewSolveOrderParamsWithTimeout creates a new SolveOrderParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSolveOrderParamsWithTimeout(timeout time.Duration) *SolveOrderParams {
	var (
		returnDevelopmentSolverRecipesDefault = bool(false)
		useRecipeStoreDefault                 = bool(true)
	)
	return &SolveOrderParams{
		ReturnDevelopmentSolverRecipes: &returnDevelopmentSolverRecipesDefault,
		UseRecipeStore:                 &useRecipeStoreDefault,

		timeout: timeout,
	}
}

// NewSolveOrderParamsWithContext creates a new SolveOrderParams object
// with the default values initialized, and the ability to set a context for a request
func NewSolveOrderParamsWithContext(ctx context.Context) *SolveOrderParams {
	var (
		returnDevelopmentSolverRecipesDefault = bool(false)
		useRecipeStoreDefault                 = bool(true)
	)
	return &SolveOrderParams{
		ReturnDevelopmentSolverRecipes: &returnDevelopmentSolverRecipesDefault,
		UseRecipeStore:                 &useRecipeStoreDefault,

		Context: ctx,
	}
}

// NewSolveOrderParamsWithHTTPClient creates a new SolveOrderParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSolveOrderParamsWithHTTPClient(client *http.Client) *SolveOrderParams {
	var (
		returnDevelopmentSolverRecipesDefault = bool(false)
		useRecipeStoreDefault                 = bool(true)
	)
	return &SolveOrderParams{
		ReturnDevelopmentSolverRecipes: &returnDevelopmentSolverRecipesDefault,
		UseRecipeStore:                 &useRecipeStoreDefault,
		HTTPClient:                     client,
	}
}

/*SolveOrderParams contains all the parameters to send to the API endpoint
for the solve order operation typically these are written to a http.Request
*/
type SolveOrderParams struct {

	/*Order*/
	Order *inventory_models.V1Order
	/*OrganizationID
	  Include ingredient information for private ingredients belong to this organization. The requesting user must be a member of the relevant organization.

	*/
	OrganizationID *string
	/*ReturnDevelopmentSolverRecipes
	  This can be used to request that the results be based on the development version of the solver, rather than the default solver. This is just present for debugging new solvers, and you should not write production code that relies on this parameter continuing to exist.

	*/
	ReturnDevelopmentSolverRecipes *bool
	/*UseRecipeStore
	  Whether to check if this order has already been solved and retrieve the result from the recipe store or, if false, to force the order to be solved anew

	*/
	UseRecipeStore *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the solve order params
func (o *SolveOrderParams) WithTimeout(timeout time.Duration) *SolveOrderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the solve order params
func (o *SolveOrderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the solve order params
func (o *SolveOrderParams) WithContext(ctx context.Context) *SolveOrderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the solve order params
func (o *SolveOrderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the solve order params
func (o *SolveOrderParams) WithHTTPClient(client *http.Client) *SolveOrderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the solve order params
func (o *SolveOrderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOrder adds the order to the solve order params
func (o *SolveOrderParams) WithOrder(order *inventory_models.V1Order) *SolveOrderParams {
	o.SetOrder(order)
	return o
}

// SetOrder adds the order to the solve order params
func (o *SolveOrderParams) SetOrder(order *inventory_models.V1Order) {
	o.Order = order
}

// WithOrganizationID adds the organizationID to the solve order params
func (o *SolveOrderParams) WithOrganizationID(organizationID *string) *SolveOrderParams {
	o.SetOrganizationID(organizationID)
	return o
}

// SetOrganizationID adds the organizationId to the solve order params
func (o *SolveOrderParams) SetOrganizationID(organizationID *string) {
	o.OrganizationID = organizationID
}

// WithReturnDevelopmentSolverRecipes adds the returnDevelopmentSolverRecipes to the solve order params
func (o *SolveOrderParams) WithReturnDevelopmentSolverRecipes(returnDevelopmentSolverRecipes *bool) *SolveOrderParams {
	o.SetReturnDevelopmentSolverRecipes(returnDevelopmentSolverRecipes)
	return o
}

// SetReturnDevelopmentSolverRecipes adds the returnDevelopmentSolverRecipes to the solve order params
func (o *SolveOrderParams) SetReturnDevelopmentSolverRecipes(returnDevelopmentSolverRecipes *bool) {
	o.ReturnDevelopmentSolverRecipes = returnDevelopmentSolverRecipes
}

// WithUseRecipeStore adds the useRecipeStore to the solve order params
func (o *SolveOrderParams) WithUseRecipeStore(useRecipeStore *bool) *SolveOrderParams {
	o.SetUseRecipeStore(useRecipeStore)
	return o
}

// SetUseRecipeStore adds the useRecipeStore to the solve order params
func (o *SolveOrderParams) SetUseRecipeStore(useRecipeStore *bool) {
	o.UseRecipeStore = useRecipeStore
}

// WriteToRequest writes these params to a swagger request
func (o *SolveOrderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Order != nil {
		if err := r.SetBodyParam(o.Order); err != nil {
			return err
		}
	}

	if o.OrganizationID != nil {

		// query param organization_id
		var qrOrganizationID string
		if o.OrganizationID != nil {
			qrOrganizationID = *o.OrganizationID
		}
		qOrganizationID := qrOrganizationID
		if qOrganizationID != "" {
			if err := r.SetQueryParam("organization_id", qOrganizationID); err != nil {
				return err
			}
		}

	}

	if o.ReturnDevelopmentSolverRecipes != nil {

		// query param return_development_solver_recipes
		var qrReturnDevelopmentSolverRecipes bool
		if o.ReturnDevelopmentSolverRecipes != nil {
			qrReturnDevelopmentSolverRecipes = *o.ReturnDevelopmentSolverRecipes
		}
		qReturnDevelopmentSolverRecipes := swag.FormatBool(qrReturnDevelopmentSolverRecipes)
		if qReturnDevelopmentSolverRecipes != "" {
			if err := r.SetQueryParam("return_development_solver_recipes", qReturnDevelopmentSolverRecipes); err != nil {
				return err
			}
		}

	}

	if o.UseRecipeStore != nil {

		// query param use_recipe_store
		var qrUseRecipeStore bool
		if o.UseRecipeStore != nil {
			qrUseRecipeStore = *o.UseRecipeStore
		}
		qUseRecipeStore := swag.FormatBool(qrUseRecipeStore)
		if qUseRecipeStore != "" {
			if err := r.SetQueryParam("use_recipe_store", qUseRecipeStore); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
