// Code generated by go-swagger; DO NOT EDIT.

package inventory_operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/ActiveState/cli/pkg/platform/api/inventory/inventory_models"
)

// NewUpdateAuthorParams creates a new UpdateAuthorParams object
// with the default values initialized.
func NewUpdateAuthorParams() *UpdateAuthorParams {
	var ()
	return &UpdateAuthorParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateAuthorParamsWithTimeout creates a new UpdateAuthorParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateAuthorParamsWithTimeout(timeout time.Duration) *UpdateAuthorParams {
	var ()
	return &UpdateAuthorParams{

		timeout: timeout,
	}
}

// NewUpdateAuthorParamsWithContext creates a new UpdateAuthorParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateAuthorParamsWithContext(ctx context.Context) *UpdateAuthorParams {
	var ()
	return &UpdateAuthorParams{

		Context: ctx,
	}
}

// NewUpdateAuthorParamsWithHTTPClient creates a new UpdateAuthorParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateAuthorParamsWithHTTPClient(client *http.Client) *UpdateAuthorParams {
	var ()
	return &UpdateAuthorParams{
		HTTPClient: client,
	}
}

/*UpdateAuthorParams contains all the parameters to send to the API endpoint
for the update author operation typically these are written to a http.Request
*/
type UpdateAuthorParams struct {

	/*Author*/
	Author *inventory_models.Author
	/*AuthorIDOrEmail*/
	AuthorIDOrEmail string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update author params
func (o *UpdateAuthorParams) WithTimeout(timeout time.Duration) *UpdateAuthorParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update author params
func (o *UpdateAuthorParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update author params
func (o *UpdateAuthorParams) WithContext(ctx context.Context) *UpdateAuthorParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update author params
func (o *UpdateAuthorParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update author params
func (o *UpdateAuthorParams) WithHTTPClient(client *http.Client) *UpdateAuthorParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update author params
func (o *UpdateAuthorParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthor adds the author to the update author params
func (o *UpdateAuthorParams) WithAuthor(author *inventory_models.Author) *UpdateAuthorParams {
	o.SetAuthor(author)
	return o
}

// SetAuthor adds the author to the update author params
func (o *UpdateAuthorParams) SetAuthor(author *inventory_models.Author) {
	o.Author = author
}

// WithAuthorIDOrEmail adds the authorIDOrEmail to the update author params
func (o *UpdateAuthorParams) WithAuthorIDOrEmail(authorIDOrEmail string) *UpdateAuthorParams {
	o.SetAuthorIDOrEmail(authorIDOrEmail)
	return o
}

// SetAuthorIDOrEmail adds the authorIdOrEmail to the update author params
func (o *UpdateAuthorParams) SetAuthorIDOrEmail(authorIDOrEmail string) {
	o.AuthorIDOrEmail = authorIDOrEmail
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateAuthorParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Author != nil {
		if err := r.SetBodyParam(o.Author); err != nil {
			return err
		}
	}

	// path param author_id_or_email
	if err := r.SetPathParam("author_id_or_email", o.AuthorIDOrEmail); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
