// Code generated by go-swagger; DO NOT EDIT.

package scans

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ActiveState/cli/pkg/platform/api/mono/mono_models"
)

// ListScansReader is a Reader for the ListScans structure.
type ListScansReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListScansReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListScansOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListScansOK creates a ListScansOK with default headers values
func NewListScansOK() *ListScansOK {
	return &ListScansOK{}
}

/*ListScansOK handles this case with default header values.

Success
*/
type ListScansOK struct {
	Payload []*mono_models.Scan
}

func (o *ListScansOK) Error() string {
	return fmt.Sprintf("[GET /scans][%d] listScansOK  %+v", 200, o.Payload)
}

func (o *ListScansOK) GetPayload() []*mono_models.Scan {
	return o.Payload
}

func (o *ListScansOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
