#! /usr/bin/env bash

function setmod-by-hrs() {
	# usage: `setmod-by-hrs -48 ../../../build/state`

	local hrs="${1}" # 10 OR -12
	local -a files=("${@:2}")
	local format="%Y%m%d%H%M.%S" # YYYYMMDDhhmm.SS
	local time="$(date --date="${1} hour" +"${format}")"

	for file in "${files[@]}"; do
		[[ ! -e "${file}" ]] && echo >&2 "skipping non-existent '${file}'" && continue
		touch -m -t "${time}" "${file}"
	done
}

setmod-by-hrs "${@}"
