if [ -f ~/.bashrc ]; then source ~/.bashrc; fi
  
if [ -z "$PROMPT_COMMAND" ]; then
    export PROMPT_COMMAND="echo -e '\033[1mActive state: ActiveState-CLI/Python3\033[0m'"
fi


export ACTIVESTATE_ACTIVATED="/tmp/610782495"

export PATH="/tmp/416043712/47b23745/Tools/ninja:/tmp/416043712/47b23745/Tools:/tmp/416043712/47b23745/bin:/go/bin/:/home/dev/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games"

export PYTHONPATH=""




cd "/tmp/610782495"