-- schema.sql
CREATE TABLE IF NOT EXISTS files (
	id INT AUTO_INCREMENT PRIMARY KEY,
	value TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS dirs (
	id INT AUTO_INCREMENT PRIMARY KEY,
	value TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS envs (
	id INT AUTO_INCREMENT PRIMARY KEY,
	value TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS rc_entries (
	id INT AUTO_INCREMENT PRIMARY KEY,
	value TEXT NOT NULL UNIQUE
);