// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

type Project struct {
	Namespace string   `json:"namespace"`
	Locations []string `json:"locations"`
}

type StateVersion struct {
	License  string `json:"license"`
	Version  string `json:"version"`
	Branch   string `json:"branch"`
	Revision string `json:"revision"`
	Date     string `json:"date"`
}

type Version struct {
	State *StateVersion `json:"state"`
}
