name: jira-description-action
"on":
  pull_request:
    types:
    - opened
    - edited
jobs:
  add-jira-description:
    runs-on: ubuntu-latest
    steps:
    - uses: cakeinpanic/jira-description-action@v0.3.2
      name: jira-description-action
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        jira-token: '${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_TOKEN }}'
        jira-base-url: https://activestatef.atlassian.net
        jira-project-key: DX
        use: branch
