name: PPM Shim deploy

on:
  push:
    paths: 
      - 'cmd/ppm/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'cmd/ppm/**'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Install State Tool
      run: |
        ./public/install.sh -n -b master
        echo "::add-path::$HOME/.local/bin"
    - name: Install the state tool
      run: public/install.sh -t $PWD
      
    - name: Build
      run: state run build-ppm

    - name: Deploy
      run: state run deploy-ppm
