name: Set-Target-PR

# === Triggers ===
"on":
  pull_request:
    types:
      - opened

# === JOBS ===
jobs:

  call-verifypr:
    uses: ./.github/workflows/verify.yml
    secrets: inherit

  # === Set target pr ===
  target-version-pr:
    name: Set target version PR
    runs-on: ubuntu-20.04
    needs: call-verifypr
    env:
      ACTIVESTATE_CLI_DISABLE_RUNTIME: true
      SHELL: bash
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      JIRA_USERNAME: ${{ secrets.JIRA_EMAIL }}
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
    timeout-minutes: 5

    steps:

      - # === Checkout code ===
        name: Checkout code
        uses: actions/checkout@v2

      - # === Install Go ===
        name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - # === Setup ===
        name: Setup
        shell: bash
        run: |
          bin=$(pwd)/.github/deps/${{ runner.os }}/bin
          echo "Adding $bin to PATH"
          echo "$bin" >> $GITHUB_PATH
          ls -ahl $bin
          printenv

      - # === Preprocess ===
        name: Preprocess
        shell: bash
        run: state run preprocess

      - # === Set Target PR ===
        name: Set Target PR
        shell: bash
        run: go run scripts/ci/target-version-pr/main.go ${{ github.event.pull_request.number }}
