#@ load("jobs.lib.yml", "jobs_build", "jobs_build_msi", "jobs_deploy", "jobs_unittest", "jobs_inttest")
#@ load("@ytt:template", "template")
name: Build-Test-Deploy

"on":
  push:
    branches:
      - master
  pull_request:

jobs:
  build: #@ jobs_build()
  build_msi: #@ jobs_build_msi()
  unittest: #@ jobs_unittest()
  inttest:
    if: 'contains(github.event.pull_request.labels.*.name, "run: integration tests")'
    _: #@ template.replace(jobs_inttest())
  deploy: #@ jobs_deploy()
