#@ load("jobs.lib.yml", "jobs_os_specific", "jobs_deploy", "jobs_unittest", "jobs_inttest", "jobs_inttestcrit", "jobs_deploy_versioned")
#@ load("@ytt:template", "template")
name: Build-Test-Deploy

"on":
  push:
    branches:
      - master
      - beta
      - release
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  os_specific: #@ jobs_os_specific()
  deploy: #@ jobs_deploy()

