#@ load("jobs.lib.yml", "jobs_prepare", "jobs_build", "jobs_deploy", "jobs_unittest", "jobs_inttest", "jobs_inttestcrit")
#@ load("@ytt:template", "template")
name: Build-Test-Deploy

"on":
  push:
    branches:
      - master
  pull_request:
    types: [labeled, synchronize, reopened]

jobs:
  prepare: #@ jobs_prepare()
  build: #@ jobs_build()
  unittest: #@ jobs_unittest()
  inttest_critical:
    if: github.ref != 'refs/heads/master'
    _: #@ template.replace(jobs_inttestcrit())
  inttest:
    if: contains(github.event.pull_request.labels.*.name, 'run integration tests')
    _: #@ template.replace(jobs_inttest())
  deploy: #@ jobs_deploy()

