name: 'Delete old artifacts'
"on":
  schedule:
    - cron: '0 0 * * *' # every day at midnight

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 2days # Delete artifacts older than a week