#@ load("steps.lib.yml", "steps_preprocess", "steps_build", "steps_build_svc", "steps_build_tray", "steps_build_installer", "steps_build_32bit", "steps_build_svc_32bit", "steps_build_tray_32bit", "steps_build_installer_32bit", "steps_genupdate", "steps_gentest_update", "steps_genupdate_32bit", "steps_installgo", "steps_setup", "steps_test", "steps_test_linux", "steps_inttestcrit", "steps_inttest", "steps_uploadartifacts", "steps_uploadsessartifacts", "steps_downloadsessartifacts", "steps_deletesessartifacts", "steps_deploy", "steps_build_state_msi", "steps_build_languages_msi", "steps_cleanbuild", "steps_sign", "steps_sign_installscript", "steps_build_installscripts", "steps_downloadallsessartifacts", "steps_sanitizeallsessartifacts", "steps_build_transition_update", "steps_build_transition_update_32bit")

#@ def strategy(fail_fast=True):
matrix:
  go-version: [1.16.x]
  platform: [ ubuntu-20.04, macos-latest, windows-latest ]
fail-fast: #@ fail_fast
#@ end

runs-on: &runs-on ${{ matrix.platform }}
env: &env
  ACTIVESTATE_CLI_DISABLE_RUNTIME: true # We don't need Perl or Python
  GOFLAGS: -mod=vendor
  SHELL: bash
  GITHUB_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#@ def jobs_build():
name: Build
strategy: #@ strategy(False)
runs-on: *runs-on
env: *env
timeout-minutes: 10
steps:
  - name: "Checkout code"
    uses: actions/checkout@v2
  - #@ steps_installgo()
  - #@ steps_setup()
  - #@ steps_preprocess()
  - #@ steps_build()
  - #@ steps_build_svc()
  - #@ steps_build_tray()
  - #@ steps_build_installer()
  - #@ steps_build_transition_update()
  - #@ steps_build_32bit()
  - #@ steps_build_svc_32bit()
  - #@ steps_build_tray_32bit()
  - #@ steps_build_installer_32bit()
  - #@ steps_build_transition_update_32bit()
  - #@ steps_build_installscripts()
  - #@ steps_sign()
  - #@ steps_sign_installscript()
  - #@ steps_genupdate()
  - #@ steps_genupdate_32bit()
  - #@ steps_build_state_msi()
  - #@ steps_build_languages_msi()
  - #@ steps_uploadsessartifacts()
#@ end

#@ def jobs_unittest():
name: "Unit Test"
strategy: #@ strategy(False)
runs-on: *runs-on
env: *env
timeout-minutes: 10
steps:
  - name: "Checkout code"
    uses: actions/checkout@v2
  - #@ steps_installgo()
  - #@ steps_setup()
  - #@ steps_preprocess()
  - #@ steps_test()
  - #@ steps_test_linux()
#@ end

#@ def jobs_inttestcrit():
name: "Critical Integration Test"
strategy: #@ strategy(False)
runs-on: *runs-on
env: *env
timeout-minutes: 25
steps:
  - name: "Checkout code"
    uses: actions/checkout@v2
  - #@ steps_installgo()
  - #@ steps_setup()
  - #@ steps_preprocess()
  - #@ steps_build()
  - #@ steps_build_svc()
  - #@ steps_build_tray()
  - #@ steps_build_installer()
  - #@ steps_build_transition_update()
  - #@ steps_genupdate()
  - #@ steps_gentest_update()
  - #@ steps_build_languages_msi()
  - #@ steps_inttestcrit()
#@ end

#@ def jobs_inttest():
name: "Integration Test"
strategy: #@ strategy(False)
runs-on: *runs-on
env: *env
timeout-minutes: 25
steps:
  - name: "Checkout code"
    uses: actions/checkout@v2
  - #@ steps_installgo()
  - #@ steps_setup()
  - #@ steps_preprocess()
  - #@ steps_build()
  - #@ steps_build_svc()
  - #@ steps_build_transition_update()
  - #@ steps_genupdate()
  - #@ steps_build_languages_msi()
  - #@ steps_inttest()
#@ end

#@ def jobs_deploy():
name: Deploy
needs: [ build, unittest ]
runs-on: ubuntu-20.04
env: *env
timeout-minutes: 10
steps:
  - name: "Checkout code"
    uses: actions/checkout@v2
  - #@ steps_installgo()
  - #@ steps_setup()
  - #@ steps_downloadallsessartifacts()
  - #@ steps_sanitizeallsessartifacts()
  - #@ steps_preprocess()
  - #@ steps_cleanbuild()
  - #@ steps_deploy()
  - #@ steps_deletesessartifacts()
  - #@ steps_uploadartifacts()
#@ end
