#@ load("steps.lib.yml", "steps_genversion", "steps_preprocess", "steps_build", "steps_genupdate", "steps_installgo", "steps_setup", "steps_test", "steps_inttest", "steps_uploadartifacts", "steps_uploadsessartifacts", "steps_downloadartifacts", "steps_downloadsessartifacts", "steps_deletesessartifacts", "steps_deploy", "steps_build_state_msi", "steps_build_languages_msi", "steps_cleanbuild", "steps_validate", "steps_sign")

strategy: &strategy
  fail-fast: false
  matrix:
    go-version: [1.13.x]
    platform: [ ubuntu-latest, macos-latest, windows-latest ]
runs-on: &runs-on ${{ matrix.platform }}
env: &env
  ACTIVESTATE_CLI_DISABLE_RUNTIME: true # We don't need Perl or Python
  GOFLAGS: -mod=vendor
  SHELL: bash
  GITHUB_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#@ def jobs_prepare():
name: "Prepare"
runs-on: ubuntu-latest
env: *env
timeout-minutes: 10
steps:
  - name: "Checkout code"
    uses: actions/checkout@v2
  - #@ steps_validate()
  - #@ steps_installgo()
  - #@ steps_setup()
  - #@ steps_genversion()
  - #@ steps_uploadsessartifacts()
#@ end

#@ def jobs_build():
name: Build
needs: [ prepare ]
strategy: *strategy
runs-on: *runs-on
env: *env
timeout-minutes: 10
steps:
  - name: "Checkout code"
    uses: actions/checkout@v2
  - #@ steps_downloadsessartifacts()
  - #@ steps_installgo()
  - #@ steps_setup()
  - #@ steps_preprocess()
  - #@ steps_build()
  - #@ steps_sign()
  - #@ steps_genupdate()
  - #@ steps_uploadsessartifacts()
#@ end

#@ def jobs_build_msi():
name: Build MSI's
runs-on: windows-latest
needs: build
env: *env
timeout-minutes: 10
steps:
  - name: "Checkout code"
    uses: actions/checkout@v2
  - #@ steps_downloadsessartifacts()
  - #@ steps_installgo()
  - #@ steps_setup()
  - #@ steps_build_state_msi()
  - #@ steps_build_languages_msi()
  - #@ steps_uploadsessartifacts()
#@ end

#@ def jobs_unittest():
name: "Unit Test"
strategy: *strategy
runs-on: *runs-on
needs: [ prepare ]
env: *env
timeout-minutes: 10
steps:
  - name: "Checkout code"
    uses: actions/checkout@v2
  - #@ steps_downloadsessartifacts()
  - #@ steps_installgo()
  - #@ steps_setup()
  - #@ steps_preprocess()
  - #@ steps_test()
#@ end

#@ def jobs_inttest():
name: "Integration Test"
strategy: *strategy
runs-on: *runs-on
env: *env
timeout-minutes: 25
needs: [ build_msi ]
steps:
  - name: "Checkout code"
    uses: actions/checkout@v2
  - #@ steps_installgo()
  - #@ steps_setup()
  - #@ steps_preprocess()
  - #@ steps_build()
  - #@ steps_downloadartifacts()
  - #@ steps_inttest()
#@ end

#@ def jobs_deploy():
name: Deploy
needs: [ build, build_msi, unittest ]
runs-on: ubuntu-latest
env: *env
timeout-minutes: 10
steps:
  - name: "Checkout code"
    uses: actions/checkout@v2
  - #@ steps_installgo()
  - #@ steps_setup()
  - #@ steps_downloadsessartifacts()
  - #@ steps_preprocess()
  - #@ steps_cleanbuild()
  - #@ steps_deploy()
  - #@ steps_deletesessartifacts()
  - #@ steps_uploadartifacts()
#@ end
