#@ load("steps.lib.yml", "steps_genversion", "steps_preprocess", "steps_build", "steps_build_32bit", "steps_genupdate", "steps_genupdate_32bit", "steps_installgo", "steps_setup", "steps_test", "steps_inttest", "steps_uploadartifacts", "steps_uploadsessartifacts", "steps_downloadsessartifacts", "steps_deletesessartifacts", "steps_deploy", "steps_build_state_msi", "steps_build_languages_msi", "steps_cleanbuild", "steps_validate", "steps_sign", "steps_sign_installscript", "steps_build_installscripts", "steps_uploadsharedartifacts", "steps_downloadsharedartifacts", "steps_downloadallsessartifacts", "steps_sanitizeallsessartifacts")

#@ def strategy(fail_fast=True):
matrix:
  go-version: [1.13.x]
  platform: [ ubuntu-latest, macos-latest, windows-latest ]
fail-fast: #@ fail_fast
#@ end

runs-on: &runs-on ${{ matrix.platform }}
env: &env
  ACTIVESTATE_CLI_DISABLE_RUNTIME: true # We don't need Perl or Python
  GOFLAGS: -mod=vendor
  SHELL: bash
  GITHUB_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#@ def jobs_prepare():
name: "Prepare"
runs-on: ubuntu-latest
env: *env
timeout-minutes: 10
steps:
  - name: "Checkout code"
    uses: actions/checkout@v2
  - #@ steps_validate()
  - #@ steps_installgo()
  - #@ steps_setup()
  - #@ steps_genversion()
  - #@ steps_uploadsharedartifacts()
#@ end

#@ def jobs_build():
name: Build
needs: [ prepare ]
strategy: #@ strategy()
runs-on: *runs-on
env: *env
timeout-minutes: 10
steps:
  - name: "Checkout code"
    uses: actions/checkout@v2
  - #@ steps_downloadsharedartifacts()
  - #@ steps_installgo()
  - #@ steps_setup()
  - #@ steps_preprocess()
  - #@ steps_build()
  - #@ steps_build_32bit()
  - #@ steps_build_installscripts()
  - #@ steps_sign()
  - #@ steps_sign_installscript()
  - #@ steps_genupdate()
  - #@ steps_genupdate_32bit()
  - #@ steps_build_state_msi()
  - #@ steps_build_languages_msi()
  - #@ steps_uploadsessartifacts()
#@ end

#@ def jobs_unittest():
name: "Unit Test"
strategy: #@ strategy()
runs-on: *runs-on
needs: [ prepare ]
env: *env
timeout-minutes: 10
steps:
  - name: "Checkout code"
    uses: actions/checkout@v2
  - #@ steps_downloadsharedartifacts()
  - #@ steps_installgo()
  - #@ steps_setup()
  - #@ steps_preprocess()
  - #@ steps_test()
#@ end

#@ def jobs_inttest():
name: "Integration Test"
strategy: #@ strategy(False)
runs-on: *runs-on
needs: [ prepare ]
env: *env
timeout-minutes: 25
steps:
  - name: "Checkout code"
    uses: actions/checkout@v2
  - #@ steps_downloadsharedartifacts()
  - #@ steps_installgo()
  - #@ steps_setup()
  - #@ steps_preprocess()
  - #@ steps_build()
  - #@ steps_genupdate()
  - #@ steps_build_languages_msi()
  - #@ steps_inttest()
#@ end

#@ def jobs_deploy():
name: Deploy
needs: [ build, unittest ]
runs-on: ubuntu-latest
env: *env
timeout-minutes: 10
steps:
  - name: "Checkout code"
    uses: actions/checkout@v2
  - #@ steps_installgo()
  - #@ steps_setup()
  - #@ steps_downloadallsessartifacts()
  - #@ steps_sanitizeallsessartifacts()
  - #@ steps_preprocess()
  - #@ steps_cleanbuild()
  - #@ steps_deploy()
  - #@ steps_deletesessartifacts()
  - #@ steps_uploadartifacts()
#@ end
